### ISSUE TITLE
Is seashells down?

### ISSUE THREAD

**Issue by CyberManifest** [anishathalye/seashells#18]
Nothing shown at links, just a blinking cursor.
Is seashells down or broken?
╭─rkm@raspberrypi ~  
╰─➤  figlet "Raspberry Pi" | lolcat | nc seashells.io 1337
serving at https://seashells.io/v/ZKWgFKJR
figlet "Raspberry Pi" | seashells
serving at https://seashells.io/v/M79rPvC2
telnet towel.blinkenlights.nl | nc seashells.io 1337

Nothing shows at link, just a blinking cursor.

**Comment by anishathalye** [comment]
If I click on those links, e.g. https://seashells.io/v/M79rPvC2, I see the expected output. Maybe this was a temporary issue? Or maybe an issue with your web browser?

**Comment by ssbarnea** [comment]
@CyberManifest Few days ago I had the same impression but it proved to be caused by my use of a HTTP proxy which did not allow websockets to pass (`wss://`).
The only bug in seashells is that it is not exposing the failure to open a web socket with the server and the only visible behavior is a blinking cursor.

Ideally it should contain an informative message.
